// <auto-generated />
using KolosTemplate.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KolosTemplate.Migrations
{
    [DbContext(typeof(CarPersonsDbContext))]
    [Migration("20220620184823_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KolosTemplate.Entities.Car", b =>
                {
                    b.Property<int>("IdCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("int");

                    b.HasKey("IdCar")
                        .HasName("Car_pk");

                    b.ToTable("Car");

                    b.HasData(
                        new
                        {
                            IdCar = 1,
                            Make = "Audi",
                            ProductionYear = 2021
                        },
                        new
                        {
                            IdCar = 2,
                            Make = "Audi",
                            ProductionYear = 2019
                        },
                        new
                        {
                            IdCar = 3,
                            Make = "Toyota",
                            ProductionYear = 2021
                        });
                });

            modelBuilder.Entity("KolosTemplate.Entities.CarPerson", b =>
                {
                    b.Property<int>("IdPerson")
                        .HasColumnType("int");

                    b.Property<int>("IdCar")
                        .HasColumnType("int");

                    b.Property<byte>("MainOwner")
                        .HasColumnType("tinyint");

                    b.HasKey("IdPerson", "IdCar")
                        .HasName("CarPerson_pk");

                    b.HasIndex("IdCar");

                    b.ToTable("Car_Person");

                    b.HasData(
                        new
                        {
                            IdPerson = 1,
                            IdCar = 1,
                            MainOwner = (byte)1
                        },
                        new
                        {
                            IdPerson = 3,
                            IdCar = 1,
                            MainOwner = (byte)0
                        },
                        new
                        {
                            IdPerson = 3,
                            IdCar = 2,
                            MainOwner = (byte)1
                        },
                        new
                        {
                            IdPerson = 2,
                            IdCar = 3,
                            MainOwner = (byte)1
                        },
                        new
                        {
                            IdPerson = 1,
                            IdCar = 3,
                            MainOwner = (byte)0
                        });
                });

            modelBuilder.Entity("KolosTemplate.Entities.Person", b =>
                {
                    b.Property<int>("IdPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DrivingLicense")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdPerson")
                        .HasName("Person_pk");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            IdPerson = 1,
                            DrivingLicense = "B",
                            Name = "Oskar",
                            Surname = "Dudzik"
                        },
                        new
                        {
                            IdPerson = 2,
                            DrivingLicense = "B",
                            Name = "Dominik",
                            Surname = "Kozluk"
                        },
                        new
                        {
                            IdPerson = 3,
                            Name = "Kacper",
                            Surname = "Godlewski"
                        });
                });

            modelBuilder.Entity("KolosTemplate.Entities.CarPerson", b =>
                {
                    b.HasOne("KolosTemplate.Entities.Car", "IdCarNavigation")
                        .WithMany("CarPersons")
                        .HasForeignKey("IdCar")
                        .HasConstraintName("CarPerson_Car")
                        .IsRequired();

                    b.HasOne("KolosTemplate.Entities.Person", "IdPersonNavigation")
                        .WithMany("CarPersons")
                        .HasForeignKey("IdPerson")
                        .HasConstraintName("CarPerson_Person")
                        .IsRequired();

                    b.Navigation("IdCarNavigation");

                    b.Navigation("IdPersonNavigation");
                });

            modelBuilder.Entity("KolosTemplate.Entities.Car", b =>
                {
                    b.Navigation("CarPersons");
                });

            modelBuilder.Entity("KolosTemplate.Entities.Person", b =>
                {
                    b.Navigation("CarPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
